GET http://localhost:3000/api/v1/tasks


# POST http://localhost:3000/api/v1/tasks
# Content-Type: application/json

# {
#   "name":"ahkfjhkasfkasdknkdnakjfnknakdnfknka"
   
# }

//get singal task
# GET http://localhost:3000/api/v1/tasks/6457653884b0b8f9ec5aa403

//UPDATE TASK
# PATCH http://localhost:3000/api/v1/tasks/645787e986c750df0bf30272
#  Content-Type: application/json

# {
#   "name":"test",
#   "completed":false
   
# }
# DELETE  http://localhost:3000/api/v1/tasks/64578877e3259f2c20daf45b
