GET http://localhost:3000/api/v1/tasks


# POST http://localhost:3000/api/v1/tasks
# Content-Type: application/json

# {
#   "name":"ahkfjhkasfkasdknkdnakjfnknakdnfknka"
   
# }

//get singal task
# GET http://localhost:3000/api/v1/tasks/sharko

//UPDATE TASK
# PATCH http://localhost:3000/api/v1/tasks/sharko

# DELETE  http://localhost:3000/api/v1/tasks/sharko
